USE [master]
GO

/****** Object:  Database [TillOrders]    Script Date: 10/27/2019 10:38:37 AM ******/
CREATE DATABASE [TillOrders]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TillOrders', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV2020\MSSQL\DATA\TillOrders.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TillOrders_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV2020\MSSQL\DATA\TillOrders_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TillOrders] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TillOrders].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TillOrders] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TillOrders] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TillOrders] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TillOrders] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TillOrders] SET ARITHABORT OFF 
GO

ALTER DATABASE [TillOrders] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TillOrders] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TillOrders] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TillOrders] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TillOrders] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TillOrders] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TillOrders] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TillOrders] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TillOrders] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TillOrders] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TillOrders] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TillOrders] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TillOrders] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TillOrders] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TillOrders] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TillOrders] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TillOrders] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TillOrders] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TillOrders] SET RECOVERY FULL 
GO

ALTER DATABASE [TillOrders] SET  MULTI_USER 
GO

ALTER DATABASE [TillOrders] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TillOrders] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TillOrders] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TillOrders] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TillOrders] SET  READ_WRITE 
GO

